#!/usr/bin/env tcsh

# Several examples for running code

# if ( $1 == "" ) then
#   set a1 = ""
# else
#   set a1 = "data=$1"
# endif

# make

# if ($? == 0) then
#   nf $a1
#   sf $a1
#   ssf $a1
#   readin $a1
# endif

# foreach x ...
#   x=(printf "%04d\n" $x)
#   make
#   nf $1
#   sf_converge $1
#   ssf $1
#   readin

foreach file (`find data/ -type f -name "*.dat" | awk -F/ '{print $2}'`)
  nf data=$file
end