#!/usr/bin/env tcsh

if ( $1 == "" ) then
  set a1 = ""
else
  set a1 = "data=$1"
endif

make

if ($? == 0) then
  nf $a1
  sf $a1
  ssf $a1
  readin
endif

#foreach x ...
#  x=(printf "%04d\n" $x)
#  make
#  nf $1
#  sf_converge $1
#  ssf $1
#  readin
